Quickstart Guides
#################

.. toctree::

        sehpc
[root@boss5osp quickstart]# cat sehpc.rst
.. include:: ../macros.rst

****************************************************
Quick Start Guide: Installing StackIQ Enterprise HPC
****************************************************

.. include:: common.txt
   :start-after: __prep__
   :end-before: __end_prep__

#.	StackIQ Enterprise HPC ISO, downloaded from the `StackIQ Website <http://www.stackiq.com/>`_.

.. include:: common.txt
   :start-after: __inst__
   :end-before: __end_inst__

#.	Wait for the :ref:`figure-welcome-qsg`.

        .. _figure-welcome-qsg:
	.. figure:: ../images/install/install-welcome-6_5.png

	        Welcome screen

        Click on **CD/DVD-based Roll**.

#.	Select the following Rolls on the :ref:`figure-roll-select-qsg`.

	* Cluster-core
	* OS
	* HPC
	* OGS
	* mlnx-ofed: Select if the cluster has Mellanox OFED Cards.
	* CUDA: Select if the cluster has NVidia Graphics cards.

        .. _figure-roll-select-qsg:
	.. figure:: ../images/install/install-select-rolls-hpc-6_6.png

	        Roll Selection Screen

	Click **Submit**.

#.	You should now be back on the original
        :ref:`Welcome Screen <figure-selected-rolls-qsg>`.
        On the left-side, you should see a list of rolls
        that have been chosen.

        .. _figure-selected-rolls-qsg:
	.. figure:: ../images/install/install-selected-rolls-hpc-6_6.png

        	Selected Rolls

	Click **Next**.

.. include:: common.txt
   :start-after: __inst2__
   :end-before: __end_inst2__